#
# Makefile for the mstar touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-y	+=  mstar_drv_common.o
obj-y	+=  mstar_drv_fw_control.o
obj-y	+=  mstar_drv_ic_fw_porting_layer.o
obj-y	+=  mstar_drv_jni_interface.o
obj-y	+=  mstar_drv_main.o
obj-y	+=  mstar_drv_mp_test.o
obj-y	+=  mstar_drv_platform_interface.o
obj-y	+=  mstar_drv_platform_porting_layer.o
obj-y	+=  mstar_drv_qcom.o
obj-y	+=  mstar_drv_utility_adaption.o
obj-y	+=  mp_test/

