#drivers/input/touchscreen/focaltech_ts/focaltech_test
#
# Makefile for test module
#
# Linux driver folder
obj-$(CONFIG_TOUCHSCREEN_FTS_3327) += focaltech_test_ft3327.o
obj-$(CONFIG_TOUCHSCREEN_FTS_3327) += focaltech_test_config_ft3327.o
obj-$(CONFIG_TOUCHSCREEN_FTS_3327) += focaltech_test_supported_ic.o

