obj-y	+=  MsgLib.o
obj-y	+=  MsgControl.o
obj-y	+=  MpTest.o
obj-y	+=  OpenTest.o
obj-y	+=  ShortTest.o
obj-y	+=  WaterProofTest.o
obj-y	+=  MsgUtility.o
obj-y	+=  TestCommon.o
obj-y	+=  IniLookup.o
obj-y	+=  CreateCSV.o
obj-y	+=  convert_file_op.o
obj-y	+=  dictionary.o
obj-y	+=  iniparser.o
obj-y	+=  my_parser.o

